# Sets, Tuples and Dictionaries

## Exercise
* Create a *tuple* ( ()-brackets) which contains the values 1,2,4,7,4,5,2
* Print the first and the second value of the *tuple*
* Print the tuple
* Use the *for loop* to print all values of this tuple
* Try to change the first value to '2'

## Exercise
* Create a *set* which contains the values 1,2,4,7,4,5,2
* Print the set
* Use the *for loop* to print all values of this set
* Try to access the first value by index

## Exercise
* Create a *list* which contains the values 8,2,5,2,4,7,9
* Use the *for loop* and two *if* conditions to calculate the minimum and maximum of all values in this list
* Tip: you'll need two variables for min and max and you need to initialize them..

##Exercise
* Create a dictionary which contains first and last name of a person, street, city as well as birthday
* Print the dictionary
* Print the first name only
* Change the value of the street
* Print the dictionary
* Add a new entry for 'country' and assign a value to this entry
* Print the dictionary

# Exercise
* Create a dictionary called data which contains two entries: month and temperature and assign list values to each entry:
** Assign a list containing values from 1 to 12 to month
** Assign a list of twelve temperature values of your choice to 'temperature'
* Print the whole dictionary
* Use a for loop to print the keys of the dictionary
* Print months values only ( choose month by index: e.g. data['month'])
* Print the values, and items of month and temperatures using a loop and the .values() and .items() method
* Use a nested loop to print all values of 'temperature' as well as 'month'. Tip: Use the *.values()* method in the first loop to retrieve the value lists.