# Variables and Operators

Some basic exercises:

To create a variable simple type its name. You need to assign a value to the variable to avoid a NameError.

Example:

`a = 1`

## Exercise
* Define a variable with a name of your choice and assign a number as value. 
* Use the `print()` method to see the value of the variable.
* Play with it: change the name of the variable, its value etc..

## Exercise
* Define a variable and assign text value to it. Use quotes 
to assigne text values e.g. : `a = 'b'`
* use the `type()` method to see the types of the variables you just created
* add some lines of code to assign an integer as well as a floating point number value to the same variable  Use the `type()` method each time

## Exercise

* Try to create a variable which begins with or contains a special character (&, @ or a number) what happens?
* Try to create a variable called 'if' and assing a value to it what happens?

## Exercise
* Create a variable and assign a value to it
* Print the result
* Assign a new value to the same variable
* print the result
* repeat

# Exercise
* Create two variables and assign values to them
* Assign variable 2 to variable 1
* Assign a new value to variable 1
* print both variables

## Exercise
* Create two variables (e.g. a and b) and assign a distinct number value to each.
* Print both variable values. 
* Then assign variable a to variable b ( `a = b` , do not reassign values).
* Print both variable values again.

## Exercise
* Create three variables e.g. a,b,c 
* assign a value to a and b
* print a and b
* switch values between a and b (tip: use c)
* print a and b

## Exercise

* You can assign one value to two or more variables in one line (`a = b = 1`) try it..
* You can assign two values to two variable in one line (`a,b = 1,2`) try it..

## Exercise
* Create a variable and assign a number value to it
* Apply a compound assignment such as += or *= and print the result

## Exercise
* Create two variables and assign a number of your choice to both
* print both variable
* Now calculate the sum of the value of the first and the second variable and assign the value to a new variable
* Now add a number (e.g. 100) to the calculated sum
* Print the result

# Exercise
* Create two variables and assign a number to it.
* Create a third variable and assign the result of some math (+,-,*) operators to it
* Print the result
* Play a bit with math operators

# Exercise
* Create two variables and assign float numbers (e.g. 5.3 and 2.1) to it 
* Print out the results of:
** a division (/) of the two variables
** a modulo division (%)
** a floor (//) division
* Whats the difference?

## Exercise
* Create some variables and assign text as well as  number value to it
* Try to apply math operators on it and print the result e.g. `print(mytext +1)`
* What happens?
* Try type casting..

## Exercise
* Use Python as a calculator and e.g. try some math operators
* print the results e.g. `print(1+2)`

4

## Exercise
Given the molar masses (g/mol) of:

> H: 1.0081

> C: 12.0112

> O: 16.0016

* Define variables for molar masses of H,C and O
* Use Python to calculate the molar mass of Aspirine (C9H8O4)
* Use Python to calculate how many moles are contained in one 1.5 kg of Aspirine

## Exercise
You have sampled 145 individuals of species a and 23 individuals of species b in a 12 l bucket. 
* Use Python to calculate number of individuals per litre
* Use Python to calculate the percentages for each species.

## Exercise

You have counted 127 individuals in the 125-500 micrometer sieve fraction which constitutes 14 % of a 32 g sediment sample.

* Use Python to calculate the number of individuals contained in one kilogram of this fraction